"""empty message

Revision ID: fd6e9001221e
Revises: 694dbf0292ef
Create Date: 2026-04-01 21:47:19.289351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6e9001221e'
down_revision = '694dbf0292ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.Boolean(), nullable=False))
        batch_op.drop_column('id_done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_done', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_done')

    # ### end Alembic commands ###
